---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

- name: Install Node.js
  apt: name=nodejs state=present

- name: Install NPM
  apt: name=npm state=present
